#!/usr/bin/env python3
"""Embed the web UI files into a PROGMEM C header for the Arduino sketch.

Usage: python3 embed_web.py <web_ui_dir> <output_header>
"""

import os
import sys


def c_escape(data):
    out = []
    for ch in data:
        o = ord(ch)
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif ch == "\n":
            out.append("\\n")
        elif ch in "\r\t":
            out.append(" ")
        elif 32 <= o < 127:
            out.append(ch)
        else:
            # Octal, not \xHH: a following hex digit would extend \x and
            # corrupt the next ASCII character (emoji became garbage in the UI).
            out.append("\\%03o" % o)
    return "".join(out)


def embed(name, path):
    with open(path, "r", encoding="utf-8") as f:
        data = f.read()
    return (
        "const char %s[] PROGMEM = \"%s\";\n"
        "const unsigned int %s_LEN = %d;\n"
        % (name, c_escape(data), name, len(data.encode("utf-8")))
    )


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else "web_ui"
    out = sys.argv[2] if len(sys.argv) > 2 else "web_assets.h"

    entries = [
        ("INDEX_HTML", os.path.join(src, "index.html")),
        ("STYLE_CSS", os.path.join(src, "style.css")),
        ("APP_JS", os.path.join(src, "app.js")),
    ]

    lines = [
        "#pragma once",
        "#include <Arduino.h>",
        "// AUTO-GENERATED by tools/embed_web.py - do not edit by hand.",
        "// Rebuild with: python3 tools/embed_web.py web_ui web_assets.h",
        "",
    ]
    for name, path in entries:
        lines.append(embed(name, path))
        lines.append("")

    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print("Generated %s (%d bytes total)" % (out, sum(len(l) for l in lines)))


if __name__ == "__main__":
    main()
